### ISSUE TITLE
Google Drive integration 

### ISSUE THREAD

**Issue by hjbwynne** [backstagetechnicalservices/website#49] opened 2018-06-23 07:45 UTC
With the move to Google Drive for event folders it would be useful to provide a link to these folders under each event page.

**Comment by bnjns** [comment] 2018-07-11 21:39
Duplicate of #53.

This issue may have been opened earlier, but #53 includes more information and additional functionality so this issue is being closed.

**Closed by bnjns** 2018-07-11 21:39 UTC
Labels: Priority: Medium, Type: New Feature, Urgency: Short Term
